# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - grown-ups-f2p-samples-app-dev-westeurope

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact for deployment
        working-directory: ./webgl-urp-2d-sample/dist
        run: zip webgl-urp-2d-sample.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./webgl-urp-2d-sample/dist/webgl-urp-2d-sample.zip

      - name: npm install
        working-directory: ./server
        run: npm install --production

      - name: Zip server for deployment
        working-directory: ./server
        run: zip server.zip ./* -r

      - name: Upload server for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Create target dir
        run: mkdir -p webgl-urp-2d-sample

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip webgl-urp-2d-sample.zip -d webgl-urp-2d-sample

      - name: Create server dir
        run: mkdir -p server

      - name: Unzip artifact for deployment
        run: unzip server.zip -d server

      - name: Remove artifact
        run: rm webgl-urp-2d-sample.zip

      - name: Remove server
        run: rm server.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52EABF2BB7D541BCA610B97069201908 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE9D504ABEC24CA49AD8285162A76751 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_288004CE13934742B7EB2FFBEB5D4459 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "grown-ups-f2p-samples-app-dev-westeurope"
          slot-name: "Production"
          package: .
